import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Line3D

# Definition of the function f
def f(x, y):
    return x**2 + y**2 + 100

# Definition of points A, vector v and vector e3
A = (1, 1, 0)
v = (1, 2, 0)
e3 = (0, 0, 1)

# Defining the range of the x and y axes
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)

# Creating the mesh for the 3D graph
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Creation of the figure and axes
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Drawing the graph of f
ax.plot_surface(X, Y, Z, cmap='viridis', alpha=0.5)

# Intersection of the graph of f with the plane generated by v and e3
t = np.linspace(-1.5, 1.5, 100)
C = v[0] * (A[0] + t * v[0]) + v[1] * (A[1] + t * v[1]) + f(A[0] + t * v[0], A[1] + t * v[1])
curve_c = ax.plot(A[0] + t * v[0], A[1] + t * v[1], C, color='orange', label='Curva C')


# Point A
point_A = ax.scatter(A[0], A[1], A[2], color='blue', s=50, label='Ponto A')

# Tangent line r
tangent_r_x = np.linspace(A[0] - 2, A[0] + 2, 100)
tangent_r_y = np.linspace(A[1] - 2, A[1] + 2, 100)
tangent_r_z = f(A[0], A[1]) + v[0] * (tangent_r_x - A[0]) + v[1] * (tangent_r_y - A[1])
tangent_r = Line3D(tangent_r_x, tangent_r_y, tangent_r_z, color='green', alpha=0.5)
ax.add_line(tangent_r)

# Vector v
vetor_v = ax.quiver(A[0], A[1], A[2], v[0], v[1], v[2], color='red', label='Vetor v')

# Corresponding point on the graph of f -> Não está a aparecer as retas até ao final dos eixos x e y
ax.plot([A[0], A[0]], [A[1], A[1]], [A[2], f(A[0], A[1])], linestyle='dashed', color='grey')
ax.plot([A[0], 0], [A[1], A[1]], [0, 0], linestyle='dashed', color='grey')
ax.plot([A[0], A[0]], [A[1], 0], [0, 0], linestyle='dashed', color='grey')

# Axes and title configuration
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_title('Gráfico de f com reta tangente r no ponto A')

# Adding the caption
ax.legend([point_A, tangent_r, vetor_v, curve_c[0]], ['Ponto A', 'Reta tangente r', 'Vetor v', 'Curva C'])

plt.show()
